/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateLifecyclePostStart;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateLifecyclePreStop;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Actions that the management system should take in response to container lifecycle events. Cannot be updated.
 */
@ApiModel(description = "Actions that the management system should take in response to container lifecycle events. Cannot be updated.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:24:47.231Z[Etc/UTC]")
public class V1alpha1PodDecorationSpecTemplateLifecycle {
  public static final String SERIALIZED_NAME_POST_START = "postStart";
  @SerializedName(SERIALIZED_NAME_POST_START)
  private V1alpha1PodDecorationSpecTemplateLifecyclePostStart postStart;

  public static final String SERIALIZED_NAME_PRE_STOP = "preStop";
  @SerializedName(SERIALIZED_NAME_PRE_STOP)
  private V1alpha1PodDecorationSpecTemplateLifecyclePreStop preStop;


  public V1alpha1PodDecorationSpecTemplateLifecycle postStart(V1alpha1PodDecorationSpecTemplateLifecyclePostStart postStart) {
    
    this.postStart = postStart;
    return this;
  }

   /**
   * Get postStart
   * @return postStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodDecorationSpecTemplateLifecyclePostStart getPostStart() {
    return postStart;
  }


  public void setPostStart(V1alpha1PodDecorationSpecTemplateLifecyclePostStart postStart) {
    this.postStart = postStart;
  }


  public V1alpha1PodDecorationSpecTemplateLifecycle preStop(V1alpha1PodDecorationSpecTemplateLifecyclePreStop preStop) {
    
    this.preStop = preStop;
    return this;
  }

   /**
   * Get preStop
   * @return preStop
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodDecorationSpecTemplateLifecyclePreStop getPreStop() {
    return preStop;
  }


  public void setPreStop(V1alpha1PodDecorationSpecTemplateLifecyclePreStop preStop) {
    this.preStop = preStop;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodDecorationSpecTemplateLifecycle v1alpha1PodDecorationSpecTemplateLifecycle = (V1alpha1PodDecorationSpecTemplateLifecycle) o;
    return Objects.equals(this.postStart, v1alpha1PodDecorationSpecTemplateLifecycle.postStart) &&
        Objects.equals(this.preStop, v1alpha1PodDecorationSpecTemplateLifecycle.preStop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postStart, preStop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodDecorationSpecTemplateLifecycle {\n");
    sb.append("    postStart: ").append(toIndentedString(postStart)).append("\n");
    sb.append("    preStop: ").append(toIndentedString(preStop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

