/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ScaleStrategy indicates the strategy detail that will be used during pod scaling.
 */
@ApiModel(description = "ScaleStrategy indicates the strategy detail that will be used during pod scaling.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:19:56.968Z[Etc/UTC]")
public class V1alpha1CollaSetSpecScaleStrategy {
  public static final String SERIALIZED_NAME_CONTEXT = "context";
  @SerializedName(SERIALIZED_NAME_CONTEXT)
  private String context;

  public static final String SERIALIZED_NAME_OPERATION_DELAY_SECONDS = "operationDelaySeconds";
  @SerializedName(SERIALIZED_NAME_OPERATION_DELAY_SECONDS)
  private Integer operationDelaySeconds;

  public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM_RETENTION_POLICY = "persistentVolumeClaimRetentionPolicy";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM_RETENTION_POLICY)
  private V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy persistentVolumeClaimRetentionPolicy;

  public static final String SERIALIZED_NAME_POD_TO_DELETE = "podToDelete";
  @SerializedName(SERIALIZED_NAME_POD_TO_DELETE)
  private List<String> podToDelete = null;

  public static final String SERIALIZED_NAME_POD_TO_EXCLUDE = "podToExclude";
  @SerializedName(SERIALIZED_NAME_POD_TO_EXCLUDE)
  private List<String> podToExclude = null;

  public static final String SERIALIZED_NAME_POD_TO_INCLUDE = "podToInclude";
  @SerializedName(SERIALIZED_NAME_POD_TO_INCLUDE)
  private List<String> podToInclude = null;


  public V1alpha1CollaSetSpecScaleStrategy context(String context) {
    
    this.context = context;
    return this;
  }

   /**
   * Context indicates the pool from which to allocate Pod instance ID. CollaSets are allowed to share the same Context. It is not allowed to change. Context defaults to be CollaSet&#39;s name.
   * @return context
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Context indicates the pool from which to allocate Pod instance ID. CollaSets are allowed to share the same Context. It is not allowed to change. Context defaults to be CollaSet's name.")

  public String getContext() {
    return context;
  }


  public void setContext(String context) {
    this.context = context;
  }


  public V1alpha1CollaSetSpecScaleStrategy operationDelaySeconds(Integer operationDelaySeconds) {
    
    this.operationDelaySeconds = operationDelaySeconds;
    return this;
  }

   /**
   * OperationDelaySeconds indicates how many seconds it should delay before operating scale.
   * @return operationDelaySeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "OperationDelaySeconds indicates how many seconds it should delay before operating scale.")

  public Integer getOperationDelaySeconds() {
    return operationDelaySeconds;
  }


  public void setOperationDelaySeconds(Integer operationDelaySeconds) {
    this.operationDelaySeconds = operationDelaySeconds;
  }


  public V1alpha1CollaSetSpecScaleStrategy persistentVolumeClaimRetentionPolicy(V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy persistentVolumeClaimRetentionPolicy) {
    
    this.persistentVolumeClaimRetentionPolicy = persistentVolumeClaimRetentionPolicy;
    return this;
  }

   /**
   * Get persistentVolumeClaimRetentionPolicy
   * @return persistentVolumeClaimRetentionPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy getPersistentVolumeClaimRetentionPolicy() {
    return persistentVolumeClaimRetentionPolicy;
  }


  public void setPersistentVolumeClaimRetentionPolicy(V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy persistentVolumeClaimRetentionPolicy) {
    this.persistentVolumeClaimRetentionPolicy = persistentVolumeClaimRetentionPolicy;
  }


  public V1alpha1CollaSetSpecScaleStrategy podToDelete(List<String> podToDelete) {
    
    this.podToDelete = podToDelete;
    return this;
  }

  public V1alpha1CollaSetSpecScaleStrategy addPodToDeleteItem(String podToDeleteItem) {
    if (this.podToDelete == null) {
      this.podToDelete = new ArrayList<>();
    }
    this.podToDelete.add(podToDeleteItem);
    return this;
  }

   /**
   * PodToDelete indicates the pods which will be deleted by CollaSet.
   * @return podToDelete
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PodToDelete indicates the pods which will be deleted by CollaSet.")

  public List<String> getPodToDelete() {
    return podToDelete;
  }


  public void setPodToDelete(List<String> podToDelete) {
    this.podToDelete = podToDelete;
  }


  public V1alpha1CollaSetSpecScaleStrategy podToExclude(List<String> podToExclude) {
    
    this.podToExclude = podToExclude;
    return this;
  }

  public V1alpha1CollaSetSpecScaleStrategy addPodToExcludeItem(String podToExcludeItem) {
    if (this.podToExclude == null) {
      this.podToExclude = new ArrayList<>();
    }
    this.podToExclude.add(podToExcludeItem);
    return this;
  }

   /**
   * PodToExclude indicates the pods which will be orphaned by CollaSet.
   * @return podToExclude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PodToExclude indicates the pods which will be orphaned by CollaSet.")

  public List<String> getPodToExclude() {
    return podToExclude;
  }


  public void setPodToExclude(List<String> podToExclude) {
    this.podToExclude = podToExclude;
  }


  public V1alpha1CollaSetSpecScaleStrategy podToInclude(List<String> podToInclude) {
    
    this.podToInclude = podToInclude;
    return this;
  }

  public V1alpha1CollaSetSpecScaleStrategy addPodToIncludeItem(String podToIncludeItem) {
    if (this.podToInclude == null) {
      this.podToInclude = new ArrayList<>();
    }
    this.podToInclude.add(podToIncludeItem);
    return this;
  }

   /**
   * PodToInclude indicates the pods which will be adapted by CollaSet.
   * @return podToInclude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PodToInclude indicates the pods which will be adapted by CollaSet.")

  public List<String> getPodToInclude() {
    return podToInclude;
  }


  public void setPodToInclude(List<String> podToInclude) {
    this.podToInclude = podToInclude;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CollaSetSpecScaleStrategy v1alpha1CollaSetSpecScaleStrategy = (V1alpha1CollaSetSpecScaleStrategy) o;
    return Objects.equals(this.context, v1alpha1CollaSetSpecScaleStrategy.context) &&
        Objects.equals(this.operationDelaySeconds, v1alpha1CollaSetSpecScaleStrategy.operationDelaySeconds) &&
        Objects.equals(this.persistentVolumeClaimRetentionPolicy, v1alpha1CollaSetSpecScaleStrategy.persistentVolumeClaimRetentionPolicy) &&
        Objects.equals(this.podToDelete, v1alpha1CollaSetSpecScaleStrategy.podToDelete) &&
        Objects.equals(this.podToExclude, v1alpha1CollaSetSpecScaleStrategy.podToExclude) &&
        Objects.equals(this.podToInclude, v1alpha1CollaSetSpecScaleStrategy.podToInclude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, operationDelaySeconds, persistentVolumeClaimRetentionPolicy, podToDelete, podToExclude, podToInclude);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CollaSetSpecScaleStrategy {\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    operationDelaySeconds: ").append(toIndentedString(operationDelaySeconds)).append("\n");
    sb.append("    persistentVolumeClaimRetentionPolicy: ").append(toIndentedString(persistentVolumeClaimRetentionPolicy)).append("\n");
    sb.append("    podToDelete: ").append(toIndentedString(podToDelete)).append("\n");
    sb.append("    podToExclude: ").append(toIndentedString(podToExclude)).append("\n");
    sb.append("    podToInclude: ").append(toIndentedString(podToInclude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

