/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodDecorationStatusPods;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1PodDecorationStatusDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:24:47.231Z[Etc/UTC]")
public class V1alpha1PodDecorationStatusDetails {
  public static final String SERIALIZED_NAME_AFFECTED_REPLICAS = "affectedReplicas";
  @SerializedName(SERIALIZED_NAME_AFFECTED_REPLICAS)
  private Integer affectedReplicas;

  public static final String SERIALIZED_NAME_COLLA_SET = "collaSet";
  @SerializedName(SERIALIZED_NAME_COLLA_SET)
  private String collaSet;

  public static final String SERIALIZED_NAME_PODS = "pods";
  @SerializedName(SERIALIZED_NAME_PODS)
  private List<V1alpha1PodDecorationStatusPods> pods = null;


  public V1alpha1PodDecorationStatusDetails affectedReplicas(Integer affectedReplicas) {
    
    this.affectedReplicas = affectedReplicas;
    return this;
  }

   /**
   * Get affectedReplicas
   * @return affectedReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAffectedReplicas() {
    return affectedReplicas;
  }


  public void setAffectedReplicas(Integer affectedReplicas) {
    this.affectedReplicas = affectedReplicas;
  }


  public V1alpha1PodDecorationStatusDetails collaSet(String collaSet) {
    
    this.collaSet = collaSet;
    return this;
  }

   /**
   * Get collaSet
   * @return collaSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCollaSet() {
    return collaSet;
  }


  public void setCollaSet(String collaSet) {
    this.collaSet = collaSet;
  }


  public V1alpha1PodDecorationStatusDetails pods(List<V1alpha1PodDecorationStatusPods> pods) {
    
    this.pods = pods;
    return this;
  }

  public V1alpha1PodDecorationStatusDetails addPodsItem(V1alpha1PodDecorationStatusPods podsItem) {
    if (this.pods == null) {
      this.pods = new ArrayList<>();
    }
    this.pods.add(podsItem);
    return this;
  }

   /**
   * Get pods
   * @return pods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1PodDecorationStatusPods> getPods() {
    return pods;
  }


  public void setPods(List<V1alpha1PodDecorationStatusPods> pods) {
    this.pods = pods;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodDecorationStatusDetails v1alpha1PodDecorationStatusDetails = (V1alpha1PodDecorationStatusDetails) o;
    return Objects.equals(this.affectedReplicas, v1alpha1PodDecorationStatusDetails.affectedReplicas) &&
        Objects.equals(this.collaSet, v1alpha1PodDecorationStatusDetails.collaSet) &&
        Objects.equals(this.pods, v1alpha1PodDecorationStatusDetails.pods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affectedReplicas, collaSet, pods);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodDecorationStatusDetails {\n");
    sb.append("    affectedReplicas: ").append(toIndentedString(affectedReplicas)).append("\n");
    sb.append("    collaSet: ").append(toIndentedString(collaSet)).append("\n");
    sb.append("    pods: ").append(toIndentedString(pods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

