/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecWebhookValueFrom;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1PodTransitionRuleSpecWebhookParameters
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleSpecWebhookParameters {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_VALUE_FROM = "valueFrom";
  @SerializedName(SERIALIZED_NAME_VALUE_FROM)
  private V1alpha1PodTransitionRuleSpecWebhookValueFrom valueFrom;


  public V1alpha1PodTransitionRuleSpecWebhookParameters key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Key is the parameter key.
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Key is the parameter key.")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public V1alpha1PodTransitionRuleSpecWebhookParameters value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Value is the string value of this parameter. Defaults to \&quot;\&quot;.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Value is the string value of this parameter. Defaults to \"\".")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public V1alpha1PodTransitionRuleSpecWebhookParameters valueFrom(V1alpha1PodTransitionRuleSpecWebhookValueFrom valueFrom) {
    
    this.valueFrom = valueFrom;
    return this;
  }

   /**
   * Get valueFrom
   * @return valueFrom
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleSpecWebhookValueFrom getValueFrom() {
    return valueFrom;
  }


  public void setValueFrom(V1alpha1PodTransitionRuleSpecWebhookValueFrom valueFrom) {
    this.valueFrom = valueFrom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleSpecWebhookParameters v1alpha1PodTransitionRuleSpecWebhookParameters = (V1alpha1PodTransitionRuleSpecWebhookParameters) o;
    return Objects.equals(this.key, v1alpha1PodTransitionRuleSpecWebhookParameters.key) &&
        Objects.equals(this.value, v1alpha1PodTransitionRuleSpecWebhookParameters.value) &&
        Objects.equals(this.valueFrom, v1alpha1PodTransitionRuleSpecWebhookParameters.valueFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value, valueFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleSpecWebhookParameters {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueFrom: ").append(toIndentedString(valueFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

