/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecWebhookClientConfig;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecWebhookParameters;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1PodTransitionRuleSpecWebhook
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleSpecWebhook {
  public static final String SERIALIZED_NAME_CLIENT_CONFIG = "clientConfig";
  @SerializedName(SERIALIZED_NAME_CLIENT_CONFIG)
  private V1alpha1PodTransitionRuleSpecWebhookClientConfig clientConfig;

  public static final String SERIALIZED_NAME_FAILURE_POLICY = "failurePolicy";
  @SerializedName(SERIALIZED_NAME_FAILURE_POLICY)
  private String failurePolicy;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<V1alpha1PodTransitionRuleSpecWebhookParameters> parameters = null;


  public V1alpha1PodTransitionRuleSpecWebhook clientConfig(V1alpha1PodTransitionRuleSpecWebhookClientConfig clientConfig) {
    
    this.clientConfig = clientConfig;
    return this;
  }

   /**
   * Get clientConfig
   * @return clientConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleSpecWebhookClientConfig getClientConfig() {
    return clientConfig;
  }


  public void setClientConfig(V1alpha1PodTransitionRuleSpecWebhookClientConfig clientConfig) {
    this.clientConfig = clientConfig;
  }


  public V1alpha1PodTransitionRuleSpecWebhook failurePolicy(String failurePolicy) {
    
    this.failurePolicy = failurePolicy;
    return this;
  }

   /**
   * FailurePolicy defines how unrecognized errors from the admission endpoint are handled - allowed values are Ignore or Fail. Defaults to Ignore.
   * @return failurePolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "FailurePolicy defines how unrecognized errors from the admission endpoint are handled - allowed values are Ignore or Fail. Defaults to Ignore.")

  public String getFailurePolicy() {
    return failurePolicy;
  }


  public void setFailurePolicy(String failurePolicy) {
    this.failurePolicy = failurePolicy;
  }


  public V1alpha1PodTransitionRuleSpecWebhook parameters(List<V1alpha1PodTransitionRuleSpecWebhookParameters> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public V1alpha1PodTransitionRuleSpecWebhook addParametersItem(V1alpha1PodTransitionRuleSpecWebhookParameters parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Parameters contains the list of parameters which will be passed in webhook body.
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Parameters contains the list of parameters which will be passed in webhook body.")

  public List<V1alpha1PodTransitionRuleSpecWebhookParameters> getParameters() {
    return parameters;
  }


  public void setParameters(List<V1alpha1PodTransitionRuleSpecWebhookParameters> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleSpecWebhook v1alpha1PodTransitionRuleSpecWebhook = (V1alpha1PodTransitionRuleSpecWebhook) o;
    return Objects.equals(this.clientConfig, v1alpha1PodTransitionRuleSpecWebhook.clientConfig) &&
        Objects.equals(this.failurePolicy, v1alpha1PodTransitionRuleSpecWebhook.failurePolicy) &&
        Objects.equals(this.parameters, v1alpha1PodTransitionRuleSpecWebhook.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientConfig, failurePolicy, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleSpecWebhook {\n");
    sb.append("    clientConfig: ").append(toIndentedString(clientConfig)).append("\n");
    sb.append("    failurePolicy: ").append(toIndentedString(failurePolicy)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

