/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateAffinity;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateContainers;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateInitContainers;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateMetadata;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplatePrimaryContainers;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateTolerations;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateVolumes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Template includes the decoration message about pod template.
 */
@ApiModel(description = "Template includes the decoration message about pod template.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:24:47.231Z[Etc/UTC]")
public class V1alpha1PodDecorationSpecTemplate {
  public static final String SERIALIZED_NAME_AFFINITY = "affinity";
  @SerializedName(SERIALIZED_NAME_AFFINITY)
  private V1alpha1PodDecorationSpecTemplateAffinity affinity;

  public static final String SERIALIZED_NAME_CONTAINERS = "containers";
  @SerializedName(SERIALIZED_NAME_CONTAINERS)
  private List<V1alpha1PodDecorationSpecTemplateContainers> containers = null;

  public static final String SERIALIZED_NAME_INIT_CONTAINERS = "initContainers";
  @SerializedName(SERIALIZED_NAME_INIT_CONTAINERS)
  private List<V1alpha1PodDecorationSpecTemplateInitContainers> initContainers = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private List<V1alpha1PodDecorationSpecTemplateMetadata> metadata = null;

  public static final String SERIALIZED_NAME_PRIMARY_CONTAINERS = "primaryContainers";
  @SerializedName(SERIALIZED_NAME_PRIMARY_CONTAINERS)
  private List<V1alpha1PodDecorationSpecTemplatePrimaryContainers> primaryContainers = null;

  public static final String SERIALIZED_NAME_RUNTIME_CLASS_NAME = "runtimeClassName";
  @SerializedName(SERIALIZED_NAME_RUNTIME_CLASS_NAME)
  private String runtimeClassName;

  public static final String SERIALIZED_NAME_TOLERATIONS = "tolerations";
  @SerializedName(SERIALIZED_NAME_TOLERATIONS)
  private List<V1alpha1PodDecorationSpecTemplateTolerations> tolerations = null;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  private List<V1alpha1PodDecorationSpecTemplateVolumes> volumes = null;


  public V1alpha1PodDecorationSpecTemplate affinity(V1alpha1PodDecorationSpecTemplateAffinity affinity) {
    
    this.affinity = affinity;
    return this;
  }

   /**
   * Get affinity
   * @return affinity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodDecorationSpecTemplateAffinity getAffinity() {
    return affinity;
  }


  public void setAffinity(V1alpha1PodDecorationSpecTemplateAffinity affinity) {
    this.affinity = affinity;
  }


  public V1alpha1PodDecorationSpecTemplate containers(List<V1alpha1PodDecorationSpecTemplateContainers> containers) {
    
    this.containers = containers;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplate addContainersItem(V1alpha1PodDecorationSpecTemplateContainers containersItem) {
    if (this.containers == null) {
      this.containers = new ArrayList<>();
    }
    this.containers.add(containersItem);
    return this;
  }

   /**
   * Containers is the containers need to be attached to a pod. If there is a container with the same name, PodDecoration will override it entirely.
   * @return containers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Containers is the containers need to be attached to a pod. If there is a container with the same name, PodDecoration will override it entirely.")

  public List<V1alpha1PodDecorationSpecTemplateContainers> getContainers() {
    return containers;
  }


  public void setContainers(List<V1alpha1PodDecorationSpecTemplateContainers> containers) {
    this.containers = containers;
  }


  public V1alpha1PodDecorationSpecTemplate initContainers(List<V1alpha1PodDecorationSpecTemplateInitContainers> initContainers) {
    
    this.initContainers = initContainers;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplate addInitContainersItem(V1alpha1PodDecorationSpecTemplateInitContainers initContainersItem) {
    if (this.initContainers == null) {
      this.initContainers = new ArrayList<>();
    }
    this.initContainers.add(initContainersItem);
    return this;
  }

   /**
   * InitContainers is the init containers needs to be attached to a pod. If there is a container with the same name, PodDecoration will retain old Container.
   * @return initContainers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "InitContainers is the init containers needs to be attached to a pod. If there is a container with the same name, PodDecoration will retain old Container.")

  public List<V1alpha1PodDecorationSpecTemplateInitContainers> getInitContainers() {
    return initContainers;
  }


  public void setInitContainers(List<V1alpha1PodDecorationSpecTemplateInitContainers> initContainers) {
    this.initContainers = initContainers;
  }


  public V1alpha1PodDecorationSpecTemplate metadata(List<V1alpha1PodDecorationSpecTemplateMetadata> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplate addMetadataItem(V1alpha1PodDecorationSpecTemplateMetadata metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

   /**
   * Metadata is the ResourceDecoration to attach on pod metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Metadata is the ResourceDecoration to attach on pod metadata")

  public List<V1alpha1PodDecorationSpecTemplateMetadata> getMetadata() {
    return metadata;
  }


  public void setMetadata(List<V1alpha1PodDecorationSpecTemplateMetadata> metadata) {
    this.metadata = metadata;
  }


  public V1alpha1PodDecorationSpecTemplate primaryContainers(List<V1alpha1PodDecorationSpecTemplatePrimaryContainers> primaryContainers) {
    
    this.primaryContainers = primaryContainers;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplate addPrimaryContainersItem(V1alpha1PodDecorationSpecTemplatePrimaryContainers primaryContainersItem) {
    if (this.primaryContainers == null) {
      this.primaryContainers = new ArrayList<>();
    }
    this.primaryContainers.add(primaryContainersItem);
    return this;
  }

   /**
   * PrimaryContainers contains the configuration to merge into the primary container. Name in it is not required. If a name indicated, then merge to the container with the matched name, otherwise merge to the one indicated by its policy.
   * @return primaryContainers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PrimaryContainers contains the configuration to merge into the primary container. Name in it is not required. If a name indicated, then merge to the container with the matched name, otherwise merge to the one indicated by its policy.")

  public List<V1alpha1PodDecorationSpecTemplatePrimaryContainers> getPrimaryContainers() {
    return primaryContainers;
  }


  public void setPrimaryContainers(List<V1alpha1PodDecorationSpecTemplatePrimaryContainers> primaryContainers) {
    this.primaryContainers = primaryContainers;
  }


  public V1alpha1PodDecorationSpecTemplate runtimeClassName(String runtimeClassName) {
    
    this.runtimeClassName = runtimeClassName;
    return this;
  }

   /**
   * RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group, which should be used to run this pod.  If no RuntimeClass resource matches the named class, the pod will not be run. If unset or empty, the \&quot;legacy\&quot; RuntimeClass will be used, which is an implicit class with an empty definition that uses the default runtime handler. More info: https://git.k8s.io/enhancements/keps/sig-node/runtime-class.md This is a beta feature as of Kubernetes v1.14.
   * @return runtimeClassName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group, which should be used to run this pod.  If no RuntimeClass resource matches the named class, the pod will not be run. If unset or empty, the \"legacy\" RuntimeClass will be used, which is an implicit class with an empty definition that uses the default runtime handler. More info: https://git.k8s.io/enhancements/keps/sig-node/runtime-class.md This is a beta feature as of Kubernetes v1.14.")

  public String getRuntimeClassName() {
    return runtimeClassName;
  }


  public void setRuntimeClassName(String runtimeClassName) {
    this.runtimeClassName = runtimeClassName;
  }


  public V1alpha1PodDecorationSpecTemplate tolerations(List<V1alpha1PodDecorationSpecTemplateTolerations> tolerations) {
    
    this.tolerations = tolerations;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplate addTolerationsItem(V1alpha1PodDecorationSpecTemplateTolerations tolerationsItem) {
    if (this.tolerations == null) {
      this.tolerations = new ArrayList<>();
    }
    this.tolerations.add(tolerationsItem);
    return this;
  }

   /**
   * If specified, the pod&#39;s tolerations.
   * @return tolerations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If specified, the pod's tolerations.")

  public List<V1alpha1PodDecorationSpecTemplateTolerations> getTolerations() {
    return tolerations;
  }


  public void setTolerations(List<V1alpha1PodDecorationSpecTemplateTolerations> tolerations) {
    this.tolerations = tolerations;
  }


  public V1alpha1PodDecorationSpecTemplate volumes(List<V1alpha1PodDecorationSpecTemplateVolumes> volumes) {
    
    this.volumes = volumes;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplate addVolumesItem(V1alpha1PodDecorationSpecTemplateVolumes volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

   /**
   * Volumes will be attached to a pod spec volume. If there is a volume with the same name, new volume will replace it.
   * @return volumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Volumes will be attached to a pod spec volume. If there is a volume with the same name, new volume will replace it.")

  public List<V1alpha1PodDecorationSpecTemplateVolumes> getVolumes() {
    return volumes;
  }


  public void setVolumes(List<V1alpha1PodDecorationSpecTemplateVolumes> volumes) {
    this.volumes = volumes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodDecorationSpecTemplate v1alpha1PodDecorationSpecTemplate = (V1alpha1PodDecorationSpecTemplate) o;
    return Objects.equals(this.affinity, v1alpha1PodDecorationSpecTemplate.affinity) &&
        Objects.equals(this.containers, v1alpha1PodDecorationSpecTemplate.containers) &&
        Objects.equals(this.initContainers, v1alpha1PodDecorationSpecTemplate.initContainers) &&
        Objects.equals(this.metadata, v1alpha1PodDecorationSpecTemplate.metadata) &&
        Objects.equals(this.primaryContainers, v1alpha1PodDecorationSpecTemplate.primaryContainers) &&
        Objects.equals(this.runtimeClassName, v1alpha1PodDecorationSpecTemplate.runtimeClassName) &&
        Objects.equals(this.tolerations, v1alpha1PodDecorationSpecTemplate.tolerations) &&
        Objects.equals(this.volumes, v1alpha1PodDecorationSpecTemplate.volumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affinity, containers, initContainers, metadata, primaryContainers, runtimeClassName, tolerations, volumes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodDecorationSpecTemplate {\n");
    sb.append("    affinity: ").append(toIndentedString(affinity)).append("\n");
    sb.append("    containers: ").append(toIndentedString(containers)).append("\n");
    sb.append("    initContainers: ").append(toIndentedString(initContainers)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    primaryContainers: ").append(toIndentedString(primaryContainers)).append("\n");
    sb.append("    runtimeClassName: ").append(toIndentedString(runtimeClassName)).append("\n");
    sb.append("    tolerations: ").append(toIndentedString(tolerations)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

