/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RollingUpdate is used to communicate parameters when Type is RollingUpdateStatefulSetStrategyType.
 */
@ApiModel(description = "RollingUpdate is used to communicate parameters when Type is RollingUpdateStatefulSetStrategyType.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:19:56.968Z[Etc/UTC]")
public class V1alpha1CollaSetSpecUpdateStrategyRollingUpdate {
  public static final String SERIALIZED_NAME_BY_LABEL = "byLabel";
  @SerializedName(SERIALIZED_NAME_BY_LABEL)
  private Object byLabel;

  public static final String SERIALIZED_NAME_BY_PARTITION = "byPartition";
  @SerializedName(SERIALIZED_NAME_BY_PARTITION)
  private V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition byPartition;


  public V1alpha1CollaSetSpecUpdateStrategyRollingUpdate byLabel(Object byLabel) {
    
    this.byLabel = byLabel;
    return this;
  }

   /**
   * ByLabel indicates the update progress is controlled by attaching pod label.
   * @return byLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ByLabel indicates the update progress is controlled by attaching pod label.")

  public Object getByLabel() {
    return byLabel;
  }


  public void setByLabel(Object byLabel) {
    this.byLabel = byLabel;
  }


  public V1alpha1CollaSetSpecUpdateStrategyRollingUpdate byPartition(V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition byPartition) {
    
    this.byPartition = byPartition;
    return this;
  }

   /**
   * Get byPartition
   * @return byPartition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition getByPartition() {
    return byPartition;
  }


  public void setByPartition(V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition byPartition) {
    this.byPartition = byPartition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CollaSetSpecUpdateStrategyRollingUpdate v1alpha1CollaSetSpecUpdateStrategyRollingUpdate = (V1alpha1CollaSetSpecUpdateStrategyRollingUpdate) o;
    return Objects.equals(this.byLabel, v1alpha1CollaSetSpecUpdateStrategyRollingUpdate.byLabel) &&
        Objects.equals(this.byPartition, v1alpha1CollaSetSpecUpdateStrategyRollingUpdate.byPartition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byLabel, byPartition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CollaSetSpecUpdateStrategyRollingUpdate {\n");
    sb.append("    byLabel: ").append(toIndentedString(byLabel)).append("\n");
    sb.append("    byPartition: ").append(toIndentedString(byPartition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

