/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1CollaSetSpecScaleStrategy;
import io.kusionstack.models.V1alpha1CollaSetSpecSelector;
import io.kusionstack.models.V1alpha1CollaSetSpecUpdateStrategy;
import io.kusionstack.models.V1alpha1CollaSetSpecVolumeClaimTemplates;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CollaSetSpec defines the desired state of CollaSet
 */
@ApiModel(description = "CollaSetSpec defines the desired state of CollaSet")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:19:56.968Z[Etc/UTC]")
public class V1alpha1CollaSetSpec {
  public static final String SERIALIZED_NAME_HISTORY_LIMIT = "historyLimit";
  @SerializedName(SERIALIZED_NAME_HISTORY_LIMIT)
  private Integer historyLimit;

  public static final String SERIALIZED_NAME_PAUSED = "paused";
  @SerializedName(SERIALIZED_NAME_PAUSED)
  private Boolean paused;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_SCALE_STRATEGY = "scaleStrategy";
  @SerializedName(SERIALIZED_NAME_SCALE_STRATEGY)
  private V1alpha1CollaSetSpecScaleStrategy scaleStrategy;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private V1alpha1CollaSetSpecSelector selector;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private Object template;

  public static final String SERIALIZED_NAME_UPDATE_STRATEGY = "updateStrategy";
  @SerializedName(SERIALIZED_NAME_UPDATE_STRATEGY)
  private V1alpha1CollaSetSpecUpdateStrategy updateStrategy;

  public static final String SERIALIZED_NAME_VOLUME_CLAIM_TEMPLATES = "volumeClaimTemplates";
  @SerializedName(SERIALIZED_NAME_VOLUME_CLAIM_TEMPLATES)
  private List<V1alpha1CollaSetSpecVolumeClaimTemplates> volumeClaimTemplates = null;


  public V1alpha1CollaSetSpec historyLimit(Integer historyLimit) {
    
    this.historyLimit = historyLimit;
    return this;
  }

   /**
   * Indicate the number of histories to be conserved If unspecified, defaults to 20
   * @return historyLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicate the number of histories to be conserved If unspecified, defaults to 20")

  public Integer getHistoryLimit() {
    return historyLimit;
  }


  public void setHistoryLimit(Integer historyLimit) {
    this.historyLimit = historyLimit;
  }


  public V1alpha1CollaSetSpec paused(Boolean paused) {
    
    this.paused = paused;
    return this;
  }

   /**
   * Indicates that the scaling and updating is paused and will not be processed by the CollaSet controller.
   * @return paused
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates that the scaling and updating is paused and will not be processed by the CollaSet controller.")

  public Boolean getPaused() {
    return paused;
  }


  public void setPaused(Boolean paused) {
    this.paused = paused;
  }


  public V1alpha1CollaSetSpec replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Replicas is the desired number of replicas of the given Template. These are replicas in the sense that they are instantiations of the same Template, but individual replicas also have a consistent identity. If unspecified, defaults to 0.
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Replicas is the desired number of replicas of the given Template. These are replicas in the sense that they are instantiations of the same Template, but individual replicas also have a consistent identity. If unspecified, defaults to 0.")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1alpha1CollaSetSpec scaleStrategy(V1alpha1CollaSetSpecScaleStrategy scaleStrategy) {
    
    this.scaleStrategy = scaleStrategy;
    return this;
  }

   /**
   * Get scaleStrategy
   * @return scaleStrategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1CollaSetSpecScaleStrategy getScaleStrategy() {
    return scaleStrategy;
  }


  public void setScaleStrategy(V1alpha1CollaSetSpecScaleStrategy scaleStrategy) {
    this.scaleStrategy = scaleStrategy;
  }


  public V1alpha1CollaSetSpec selector(V1alpha1CollaSetSpecSelector selector) {
    
    this.selector = selector;
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1CollaSetSpecSelector getSelector() {
    return selector;
  }


  public void setSelector(V1alpha1CollaSetSpecSelector selector) {
    this.selector = selector;
  }


  public V1alpha1CollaSetSpec template(Object template) {
    
    this.template = template;
    return this;
  }

   /**
   * Template is the object that describes the pod that will be created if insufficient replicas are detected. Each pod stamped out by the CollaSet will fulfill this Template, but have a unique identity from the rest of the CollaSet.
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Template is the object that describes the pod that will be created if insufficient replicas are detected. Each pod stamped out by the CollaSet will fulfill this Template, but have a unique identity from the rest of the CollaSet.")

  public Object getTemplate() {
    return template;
  }


  public void setTemplate(Object template) {
    this.template = template;
  }


  public V1alpha1CollaSetSpec updateStrategy(V1alpha1CollaSetSpecUpdateStrategy updateStrategy) {
    
    this.updateStrategy = updateStrategy;
    return this;
  }

   /**
   * Get updateStrategy
   * @return updateStrategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1CollaSetSpecUpdateStrategy getUpdateStrategy() {
    return updateStrategy;
  }


  public void setUpdateStrategy(V1alpha1CollaSetSpecUpdateStrategy updateStrategy) {
    this.updateStrategy = updateStrategy;
  }


  public V1alpha1CollaSetSpec volumeClaimTemplates(List<V1alpha1CollaSetSpecVolumeClaimTemplates> volumeClaimTemplates) {
    
    this.volumeClaimTemplates = volumeClaimTemplates;
    return this;
  }

  public V1alpha1CollaSetSpec addVolumeClaimTemplatesItem(V1alpha1CollaSetSpecVolumeClaimTemplates volumeClaimTemplatesItem) {
    if (this.volumeClaimTemplates == null) {
      this.volumeClaimTemplates = new ArrayList<>();
    }
    this.volumeClaimTemplates.add(volumeClaimTemplatesItem);
    return this;
  }

   /**
   * VolumeClaimTemplates is a list of claims that pods are allowed to reference. The StatefulSet controller is responsible for mapping network identities to claims in a way that maintains the identity of a pod. Every claim in this list must have at least one matching (by name) volumeMount in one container in the template. A claim in this list takes precedence over any volumes in the template, with the same name.
   * @return volumeClaimTemplates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VolumeClaimTemplates is a list of claims that pods are allowed to reference. The StatefulSet controller is responsible for mapping network identities to claims in a way that maintains the identity of a pod. Every claim in this list must have at least one matching (by name) volumeMount in one container in the template. A claim in this list takes precedence over any volumes in the template, with the same name.")

  public List<V1alpha1CollaSetSpecVolumeClaimTemplates> getVolumeClaimTemplates() {
    return volumeClaimTemplates;
  }


  public void setVolumeClaimTemplates(List<V1alpha1CollaSetSpecVolumeClaimTemplates> volumeClaimTemplates) {
    this.volumeClaimTemplates = volumeClaimTemplates;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CollaSetSpec v1alpha1CollaSetSpec = (V1alpha1CollaSetSpec) o;
    return Objects.equals(this.historyLimit, v1alpha1CollaSetSpec.historyLimit) &&
        Objects.equals(this.paused, v1alpha1CollaSetSpec.paused) &&
        Objects.equals(this.replicas, v1alpha1CollaSetSpec.replicas) &&
        Objects.equals(this.scaleStrategy, v1alpha1CollaSetSpec.scaleStrategy) &&
        Objects.equals(this.selector, v1alpha1CollaSetSpec.selector) &&
        Objects.equals(this.template, v1alpha1CollaSetSpec.template) &&
        Objects.equals(this.updateStrategy, v1alpha1CollaSetSpec.updateStrategy) &&
        Objects.equals(this.volumeClaimTemplates, v1alpha1CollaSetSpec.volumeClaimTemplates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(historyLimit, paused, replicas, scaleStrategy, selector, template, updateStrategy, volumeClaimTemplates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CollaSetSpec {\n");
    sb.append("    historyLimit: ").append(toIndentedString(historyLimit)).append("\n");
    sb.append("    paused: ").append(toIndentedString(paused)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    scaleStrategy: ").append(toIndentedString(scaleStrategy)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    updateStrategy: ").append(toIndentedString(updateStrategy)).append("\n");
    sb.append("    volumeClaimTemplates: ").append(toIndentedString(volumeClaimTemplates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

