/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecRules;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecSelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PodTransitionRuleSpec defines the desired state of PodTransitionRule
 */
@ApiModel(description = "PodTransitionRuleSpec defines the desired state of PodTransitionRule")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleSpec {
  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<V1alpha1PodTransitionRuleSpecRules> rules = null;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private V1alpha1PodTransitionRuleSpecSelector selector;


  public V1alpha1PodTransitionRuleSpec rules(List<V1alpha1PodTransitionRuleSpecRules> rules) {
    
    this.rules = rules;
    return this;
  }

  public V1alpha1PodTransitionRuleSpec addRulesItem(V1alpha1PodTransitionRuleSpecRules rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Rules is a set of rules that need to be checked in certain situations
   * @return rules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Rules is a set of rules that need to be checked in certain situations")

  public List<V1alpha1PodTransitionRuleSpecRules> getRules() {
    return rules;
  }


  public void setRules(List<V1alpha1PodTransitionRuleSpecRules> rules) {
    this.rules = rules;
  }


  public V1alpha1PodTransitionRuleSpec selector(V1alpha1PodTransitionRuleSpecSelector selector) {
    
    this.selector = selector;
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleSpecSelector getSelector() {
    return selector;
  }


  public void setSelector(V1alpha1PodTransitionRuleSpecSelector selector) {
    this.selector = selector;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleSpec v1alpha1PodTransitionRuleSpec = (V1alpha1PodTransitionRuleSpec) o;
    return Objects.equals(this.rules, v1alpha1PodTransitionRuleSpec.rules) &&
        Objects.equals(this.selector, v1alpha1PodTransitionRuleSpec.selector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rules, selector);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleSpec {\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

