/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ByPartition indicates the update progress is controlled by partition value.
 */
@ApiModel(description = "ByPartition indicates the update progress is controlled by partition value.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:19:56.968Z[Etc/UTC]")
public class V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition {
  public static final String SERIALIZED_NAME_PARTITION = "partition";
  @SerializedName(SERIALIZED_NAME_PARTITION)
  private Integer partition;


  public V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition partition(Integer partition) {
    
    this.partition = partition;
    return this;
  }

   /**
   * Partition controls the number of pods in old revisions. Defaults to nil (all pods will be updated)
   * @return partition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Partition controls the number of pods in old revisions. Defaults to nil (all pods will be updated)")

  public Integer getPartition() {
    return partition;
  }


  public void setPartition(Integer partition) {
    this.partition = partition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition v1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition = (V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition) o;
    return Objects.equals(this.partition, v1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition.partition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CollaSetSpecUpdateStrategyRollingUpdateByPartition {\n");
    sb.append("    partition: ").append(toIndentedString(partition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

