/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleStatusWebhookStatusHistory;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WebhookStatus is the webhook status representing processing progress
 */
@ApiModel(description = "WebhookStatus is the webhook status representing processing progress")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleStatusWebhookStatus {
  public static final String SERIALIZED_NAME_HISTORY = "history";
  @SerializedName(SERIALIZED_NAME_HISTORY)
  private List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> history = null;

  public static final String SERIALIZED_NAME_TASK_STATES = "taskStates";
  @SerializedName(SERIALIZED_NAME_TASK_STATES)
  private List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> taskStates = null;


  public V1alpha1PodTransitionRuleStatusWebhookStatus history(List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> history) {
    
    this.history = history;
    return this;
  }

  public V1alpha1PodTransitionRuleStatusWebhookStatus addHistoryItem(V1alpha1PodTransitionRuleStatusWebhookStatusHistory historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<>();
    }
    this.history.add(historyItem);
    return this;
  }

   /**
   * History records history taskStates which were finished or failed. Valid for 10 minutes
   * @return history
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "History records history taskStates which were finished or failed. Valid for 10 minutes")

  public List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> getHistory() {
    return history;
  }


  public void setHistory(List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> history) {
    this.history = history;
  }


  public V1alpha1PodTransitionRuleStatusWebhookStatus taskStates(List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> taskStates) {
    
    this.taskStates = taskStates;
    return this;
  }

  public V1alpha1PodTransitionRuleStatusWebhookStatus addTaskStatesItem(V1alpha1PodTransitionRuleStatusWebhookStatusHistory taskStatesItem) {
    if (this.taskStates == null) {
      this.taskStates = new ArrayList<>();
    }
    this.taskStates.add(taskStatesItem);
    return this;
  }

   /**
   * TaskStates is a list of tracing info
   * @return taskStates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TaskStates is a list of tracing info")

  public List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> getTaskStates() {
    return taskStates;
  }


  public void setTaskStates(List<V1alpha1PodTransitionRuleStatusWebhookStatusHistory> taskStates) {
    this.taskStates = taskStates;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleStatusWebhookStatus v1alpha1PodTransitionRuleStatusWebhookStatus = (V1alpha1PodTransitionRuleStatusWebhookStatus) o;
    return Objects.equals(this.history, v1alpha1PodTransitionRuleStatusWebhookStatus.history) &&
        Objects.equals(this.taskStates, v1alpha1PodTransitionRuleStatusWebhookStatus.taskStates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(history, taskStates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleStatusWebhookStatus {\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    taskStates: ").append(toIndentedString(taskStates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

