/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecAvailablePolicy;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecFilter;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecLabelCheck;
import io.kusionstack.models.V1alpha1PodTransitionRuleSpecWebhook;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1PodTransitionRuleSpecRules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleSpecRules {
  public static final String SERIALIZED_NAME_AVAILABLE_POLICY = "availablePolicy";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_POLICY)
  private V1alpha1PodTransitionRuleSpecAvailablePolicy availablePolicy;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<String> conditions = null;

  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  private Boolean disabled;

  public static final String SERIALIZED_NAME_FILTER = "filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  private V1alpha1PodTransitionRuleSpecFilter filter;

  public static final String SERIALIZED_NAME_LABEL_CHECK = "labelCheck";
  @SerializedName(SERIALIZED_NAME_LABEL_CHECK)
  private V1alpha1PodTransitionRuleSpecLabelCheck labelCheck;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  private String stage;

  public static final String SERIALIZED_NAME_WEBHOOK = "webhook";
  @SerializedName(SERIALIZED_NAME_WEBHOOK)
  private V1alpha1PodTransitionRuleSpecWebhook webhook;


  public V1alpha1PodTransitionRuleSpecRules availablePolicy(V1alpha1PodTransitionRuleSpecAvailablePolicy availablePolicy) {
    
    this.availablePolicy = availablePolicy;
    return this;
  }

   /**
   * Get availablePolicy
   * @return availablePolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleSpecAvailablePolicy getAvailablePolicy() {
    return availablePolicy;
  }


  public void setAvailablePolicy(V1alpha1PodTransitionRuleSpecAvailablePolicy availablePolicy) {
    this.availablePolicy = availablePolicy;
  }


  public V1alpha1PodTransitionRuleSpecRules conditions(List<String> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha1PodTransitionRuleSpecRules addConditionsItem(String conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions is the condition to control this rule enable or not.
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Conditions is the condition to control this rule enable or not.")

  public List<String> getConditions() {
    return conditions;
  }


  public void setConditions(List<String> conditions) {
    this.conditions = conditions;
  }


  public V1alpha1PodTransitionRuleSpecRules disabled(Boolean disabled) {
    
    this.disabled = disabled;
    return this;
  }

   /**
   * Disabled is the switch to control this rule enable or not.
   * @return disabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disabled is the switch to control this rule enable or not.")

  public Boolean getDisabled() {
    return disabled;
  }


  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


  public V1alpha1PodTransitionRuleSpecRules filter(V1alpha1PodTransitionRuleSpecFilter filter) {
    
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleSpecFilter getFilter() {
    return filter;
  }


  public void setFilter(V1alpha1PodTransitionRuleSpecFilter filter) {
    this.filter = filter;
  }


  public V1alpha1PodTransitionRuleSpecRules labelCheck(V1alpha1PodTransitionRuleSpecLabelCheck labelCheck) {
    
    this.labelCheck = labelCheck;
    return this;
  }

   /**
   * Get labelCheck
   * @return labelCheck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleSpecLabelCheck getLabelCheck() {
    return labelCheck;
  }


  public void setLabelCheck(V1alpha1PodTransitionRuleSpecLabelCheck labelCheck) {
    this.labelCheck = labelCheck;
  }


  public V1alpha1PodTransitionRuleSpecRules name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is the name of this rule.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name is the name of this rule.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1PodTransitionRuleSpecRules stage(String stage) {
    
    this.stage = stage;
    return this;
  }

   /**
   * Get stage
   * @return stage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStage() {
    return stage;
  }


  public void setStage(String stage) {
    this.stage = stage;
  }


  public V1alpha1PodTransitionRuleSpecRules webhook(V1alpha1PodTransitionRuleSpecWebhook webhook) {
    
    this.webhook = webhook;
    return this;
  }

   /**
   * Get webhook
   * @return webhook
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleSpecWebhook getWebhook() {
    return webhook;
  }


  public void setWebhook(V1alpha1PodTransitionRuleSpecWebhook webhook) {
    this.webhook = webhook;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleSpecRules v1alpha1PodTransitionRuleSpecRules = (V1alpha1PodTransitionRuleSpecRules) o;
    return Objects.equals(this.availablePolicy, v1alpha1PodTransitionRuleSpecRules.availablePolicy) &&
        Objects.equals(this.conditions, v1alpha1PodTransitionRuleSpecRules.conditions) &&
        Objects.equals(this.disabled, v1alpha1PodTransitionRuleSpecRules.disabled) &&
        Objects.equals(this.filter, v1alpha1PodTransitionRuleSpecRules.filter) &&
        Objects.equals(this.labelCheck, v1alpha1PodTransitionRuleSpecRules.labelCheck) &&
        Objects.equals(this.name, v1alpha1PodTransitionRuleSpecRules.name) &&
        Objects.equals(this.stage, v1alpha1PodTransitionRuleSpecRules.stage) &&
        Objects.equals(this.webhook, v1alpha1PodTransitionRuleSpecRules.webhook);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availablePolicy, conditions, disabled, filter, labelCheck, name, stage, webhook);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleSpecRules {\n");
    sb.append("    availablePolicy: ").append(toIndentedString(availablePolicy)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    labelCheck: ").append(toIndentedString(labelCheck)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

