/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AvailablePolicy is the rule to check if the max unavailable number is reached by current resource updated.
 */
@ApiModel(description = "AvailablePolicy is the rule to check if the max unavailable number is reached by current resource updated.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleSpecAvailablePolicy {
  public static final String SERIALIZED_NAME_MAX_UNAVAILABLE_VALUE = "maxUnavailableValue";
  @SerializedName(SERIALIZED_NAME_MAX_UNAVAILABLE_VALUE)
  private Object maxUnavailableValue;

  public static final String SERIALIZED_NAME_MIN_AVAILABLE_VALUE = "minAvailableValue";
  @SerializedName(SERIALIZED_NAME_MIN_AVAILABLE_VALUE)
  private Object minAvailableValue;


  public V1alpha1PodTransitionRuleSpecAvailablePolicy maxUnavailableValue(Object maxUnavailableValue) {
    
    this.maxUnavailableValue = maxUnavailableValue;
    return this;
  }

   /**
   * MaxUnavailableValue is the expected max unavailable replicas which is allowed to be a integer or a percentage of the whole number of the target resources.
   * @return maxUnavailableValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MaxUnavailableValue is the expected max unavailable replicas which is allowed to be a integer or a percentage of the whole number of the target resources.")

  public Object getMaxUnavailableValue() {
    return maxUnavailableValue;
  }


  public void setMaxUnavailableValue(Object maxUnavailableValue) {
    this.maxUnavailableValue = maxUnavailableValue;
  }


  public V1alpha1PodTransitionRuleSpecAvailablePolicy minAvailableValue(Object minAvailableValue) {
    
    this.minAvailableValue = minAvailableValue;
    return this;
  }

   /**
   * MinAvailableValue is the expected min available replicas which is allowed to be a integer or a percentage of the whole number of the target resources.
   * @return minAvailableValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MinAvailableValue is the expected min available replicas which is allowed to be a integer or a percentage of the whole number of the target resources.")

  public Object getMinAvailableValue() {
    return minAvailableValue;
  }


  public void setMinAvailableValue(Object minAvailableValue) {
    this.minAvailableValue = minAvailableValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleSpecAvailablePolicy v1alpha1PodTransitionRuleSpecAvailablePolicy = (V1alpha1PodTransitionRuleSpecAvailablePolicy) o;
    return Objects.equals(this.maxUnavailableValue, v1alpha1PodTransitionRuleSpecAvailablePolicy.maxUnavailableValue) &&
        Objects.equals(this.minAvailableValue, v1alpha1PodTransitionRuleSpecAvailablePolicy.minAvailableValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxUnavailableValue, minAvailableValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleSpecAvailablePolicy {\n");
    sb.append("    maxUnavailableValue: ").append(toIndentedString(maxUnavailableValue)).append("\n");
    sb.append("    minAvailableValue: ").append(toIndentedString(minAvailableValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

