/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PersistentVolumeClaimRetentionPolicy describes the lifecycle of PersistentVolumeClaim created from volumeClaimTemplates. By default, all persistent volume claims are created as needed and deleted after no pod is using them. This policy allows the lifecycle to be altered, for example by deleting persistent volume claims when their CollaSet is deleted, or when their pod is scaled down.
 */
@ApiModel(description = "PersistentVolumeClaimRetentionPolicy describes the lifecycle of PersistentVolumeClaim created from volumeClaimTemplates. By default, all persistent volume claims are created as needed and deleted after no pod is using them. This policy allows the lifecycle to be altered, for example by deleting persistent volume claims when their CollaSet is deleted, or when their pod is scaled down.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:19:56.968Z[Etc/UTC]")
public class V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy {
  public static final String SERIALIZED_NAME_WHEN_DELETED = "whenDeleted";
  @SerializedName(SERIALIZED_NAME_WHEN_DELETED)
  private String whenDeleted;

  public static final String SERIALIZED_NAME_WHEN_SCALED = "whenScaled";
  @SerializedName(SERIALIZED_NAME_WHEN_SCALED)
  private String whenScaled;


  public V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy whenDeleted(String whenDeleted) {
    
    this.whenDeleted = whenDeleted;
    return this;
  }

   /**
   * WhenDeleted specifies what happens to PVCs created from CollaSet VolumeClaimTemplates when the CollaSet is deleted. The default policy of &#x60;Delete&#x60; policy causes those PVCs to be deleted. &#x60;Retain&#x60; causes PVCs to not be affected by StatefulSet deletion. The
   * @return whenDeleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "WhenDeleted specifies what happens to PVCs created from CollaSet VolumeClaimTemplates when the CollaSet is deleted. The default policy of `Delete` policy causes those PVCs to be deleted. `Retain` causes PVCs to not be affected by StatefulSet deletion. The")

  public String getWhenDeleted() {
    return whenDeleted;
  }


  public void setWhenDeleted(String whenDeleted) {
    this.whenDeleted = whenDeleted;
  }


  public V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy whenScaled(String whenScaled) {
    
    this.whenScaled = whenScaled;
    return this;
  }

   /**
   * WhenScaled specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is scaled down. The default policy of &#x60;Retain&#x60; causes PVCs to not be affected by a scaledown. The &#x60;Delete&#x60; policy causes the associated PVCs for any excess pods above the replica count to be deleted.
   * @return whenScaled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "WhenScaled specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is scaled down. The default policy of `Retain` causes PVCs to not be affected by a scaledown. The `Delete` policy causes the associated PVCs for any excess pods above the replica count to be deleted.")

  public String getWhenScaled() {
    return whenScaled;
  }


  public void setWhenScaled(String whenScaled) {
    this.whenScaled = whenScaled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy v1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy = (V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy) o;
    return Objects.equals(this.whenDeleted, v1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy.whenDeleted) &&
        Objects.equals(this.whenScaled, v1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy.whenScaled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(whenDeleted, whenScaled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CollaSetSpecScaleStrategyPersistentVolumeClaimRetentionPolicy {\n");
    sb.append("    whenDeleted: ").append(toIndentedString(whenDeleted)).append("\n");
    sb.append("    whenScaled: ").append(toIndentedString(whenScaled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

