/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleStatusRejectInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1PodTransitionRuleStatusDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleStatusDetails {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PASSED = "passed";
  @SerializedName(SERIALIZED_NAME_PASSED)
  private Boolean passed;

  public static final String SERIALIZED_NAME_PASSED_RULES = "passedRules";
  @SerializedName(SERIALIZED_NAME_PASSED_RULES)
  private List<String> passedRules = null;

  public static final String SERIALIZED_NAME_REJECT_INFO = "rejectInfo";
  @SerializedName(SERIALIZED_NAME_REJECT_INFO)
  private List<V1alpha1PodTransitionRuleStatusRejectInfo> rejectInfo = null;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  private String stage;


  public V1alpha1PodTransitionRuleStatusDetails name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name representing Pod name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name representing Pod name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1PodTransitionRuleStatusDetails passed(Boolean passed) {
    
    this.passed = passed;
    return this;
  }

   /**
   * Passed indicates whether the pod passed all rules
   * @return passed
  **/
  @ApiModelProperty(required = true, value = "Passed indicates whether the pod passed all rules")

  public Boolean getPassed() {
    return passed;
  }


  public void setPassed(Boolean passed) {
    this.passed = passed;
  }


  public V1alpha1PodTransitionRuleStatusDetails passedRules(List<String> passedRules) {
    
    this.passedRules = passedRules;
    return this;
  }

  public V1alpha1PodTransitionRuleStatusDetails addPassedRulesItem(String passedRulesItem) {
    if (this.passedRules == null) {
      this.passedRules = new ArrayList<>();
    }
    this.passedRules.add(passedRulesItem);
    return this;
  }

   /**
   * Get passedRules
   * @return passedRules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPassedRules() {
    return passedRules;
  }


  public void setPassedRules(List<String> passedRules) {
    this.passedRules = passedRules;
  }


  public V1alpha1PodTransitionRuleStatusDetails rejectInfo(List<V1alpha1PodTransitionRuleStatusRejectInfo> rejectInfo) {
    
    this.rejectInfo = rejectInfo;
    return this;
  }

  public V1alpha1PodTransitionRuleStatusDetails addRejectInfoItem(V1alpha1PodTransitionRuleStatusRejectInfo rejectInfoItem) {
    if (this.rejectInfo == null) {
      this.rejectInfo = new ArrayList<>();
    }
    this.rejectInfo.add(rejectInfoItem);
    return this;
  }

   /**
   * Get rejectInfo
   * @return rejectInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1PodTransitionRuleStatusRejectInfo> getRejectInfo() {
    return rejectInfo;
  }


  public void setRejectInfo(List<V1alpha1PodTransitionRuleStatusRejectInfo> rejectInfo) {
    this.rejectInfo = rejectInfo;
  }


  public V1alpha1PodTransitionRuleStatusDetails stage(String stage) {
    
    this.stage = stage;
    return this;
  }

   /**
   * Stage is pod current stage
   * @return stage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Stage is pod current stage")

  public String getStage() {
    return stage;
  }


  public void setStage(String stage) {
    this.stage = stage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleStatusDetails v1alpha1PodTransitionRuleStatusDetails = (V1alpha1PodTransitionRuleStatusDetails) o;
    return Objects.equals(this.name, v1alpha1PodTransitionRuleStatusDetails.name) &&
        Objects.equals(this.passed, v1alpha1PodTransitionRuleStatusDetails.passed) &&
        Objects.equals(this.passedRules, v1alpha1PodTransitionRuleStatusDetails.passedRules) &&
        Objects.equals(this.rejectInfo, v1alpha1PodTransitionRuleStatusDetails.rejectInfo) &&
        Objects.equals(this.stage, v1alpha1PodTransitionRuleStatusDetails.stage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, passed, passedRules, rejectInfo, stage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleStatusDetails {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    passed: ").append(toIndentedString(passed)).append("\n");
    sb.append("    passedRules: ").append(toIndentedString(passedRules)).append("\n");
    sb.append("    rejectInfo: ").append(toIndentedString(rejectInfo)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

