/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleStatusWebhookStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RuleState defines the resource info in webhook processing progress.
 */
@ApiModel(description = "RuleState defines the resource info in webhook processing progress.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleStatusRuleStates {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_WEBHOOK_STATUS = "webhookStatus";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_STATUS)
  private V1alpha1PodTransitionRuleStatusWebhookStatus webhookStatus;


  public V1alpha1PodTransitionRuleStatusRuleStates name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is the name representing the rule
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name is the name representing the rule")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1PodTransitionRuleStatusRuleStates webhookStatus(V1alpha1PodTransitionRuleStatusWebhookStatus webhookStatus) {
    
    this.webhookStatus = webhookStatus;
    return this;
  }

   /**
   * Get webhookStatus
   * @return webhookStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTransitionRuleStatusWebhookStatus getWebhookStatus() {
    return webhookStatus;
  }


  public void setWebhookStatus(V1alpha1PodTransitionRuleStatusWebhookStatus webhookStatus) {
    this.webhookStatus = webhookStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleStatusRuleStates v1alpha1PodTransitionRuleStatusRuleStates = (V1alpha1PodTransitionRuleStatusRuleStates) o;
    return Objects.equals(this.name, v1alpha1PodTransitionRuleStatusRuleStates.name) &&
        Objects.equals(this.webhookStatus, v1alpha1PodTransitionRuleStatusRuleStates.webhookStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, webhookStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleStatusRuleStates {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    webhookStatus: ").append(toIndentedString(webhookStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

