/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1PodTransitionRuleStatusWebhookStatusHistory
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleStatusWebhookStatusHistory {
  public static final String SERIALIZED_NAME_APPROVED = "approved";
  @SerializedName(SERIALIZED_NAME_APPROVED)
  private List<String> approved = null;

  public static final String SERIALIZED_NAME_BEGIN_TIME = "beginTime";
  @SerializedName(SERIALIZED_NAME_BEGIN_TIME)
  private OffsetDateTime beginTime;

  public static final String SERIALIZED_NAME_LAST_TIME = "lastTime";
  @SerializedName(SERIALIZED_NAME_LAST_TIME)
  private OffsetDateTime lastTime;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PROCESSING = "processing";
  @SerializedName(SERIALIZED_NAME_PROCESSING)
  private List<String> processing = null;

  public static final String SERIALIZED_NAME_TASK_ID = "taskId";
  @SerializedName(SERIALIZED_NAME_TASK_ID)
  private String taskId;


  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory approved(List<String> approved) {
    
    this.approved = approved;
    return this;
  }

  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory addApprovedItem(String approvedItem) {
    if (this.approved == null) {
      this.approved = new ArrayList<>();
    }
    this.approved.add(approvedItem);
    return this;
  }

   /**
   * Get approved
   * @return approved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getApproved() {
    return approved;
  }


  public void setApproved(List<String> approved) {
    this.approved = approved;
  }


  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory beginTime(OffsetDateTime beginTime) {
    
    this.beginTime = beginTime;
    return this;
  }

   /**
   * Get beginTime
   * @return beginTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getBeginTime() {
    return beginTime;
  }


  public void setBeginTime(OffsetDateTime beginTime) {
    this.beginTime = beginTime;
  }


  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory lastTime(OffsetDateTime lastTime) {
    
    this.lastTime = lastTime;
    return this;
  }

   /**
   * Get lastTime
   * @return lastTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastTime() {
    return lastTime;
  }


  public void setLastTime(OffsetDateTime lastTime) {
    this.lastTime = lastTime;
  }


  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory processing(List<String> processing) {
    
    this.processing = processing;
    return this;
  }

  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory addProcessingItem(String processingItem) {
    if (this.processing == null) {
      this.processing = new ArrayList<>();
    }
    this.processing.add(processingItem);
    return this;
  }

   /**
   * Get processing
   * @return processing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getProcessing() {
    return processing;
  }


  public void setProcessing(List<String> processing) {
    this.processing = processing;
  }


  public V1alpha1PodTransitionRuleStatusWebhookStatusHistory taskId(String taskId) {
    
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTaskId() {
    return taskId;
  }


  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleStatusWebhookStatusHistory v1alpha1PodTransitionRuleStatusWebhookStatusHistory = (V1alpha1PodTransitionRuleStatusWebhookStatusHistory) o;
    return Objects.equals(this.approved, v1alpha1PodTransitionRuleStatusWebhookStatusHistory.approved) &&
        Objects.equals(this.beginTime, v1alpha1PodTransitionRuleStatusWebhookStatusHistory.beginTime) &&
        Objects.equals(this.lastTime, v1alpha1PodTransitionRuleStatusWebhookStatusHistory.lastTime) &&
        Objects.equals(this.message, v1alpha1PodTransitionRuleStatusWebhookStatusHistory.message) &&
        Objects.equals(this.processing, v1alpha1PodTransitionRuleStatusWebhookStatusHistory.processing) &&
        Objects.equals(this.taskId, v1alpha1PodTransitionRuleStatusWebhookStatusHistory.taskId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approved, beginTime, lastTime, message, processing, taskId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleStatusWebhookStatusHistory {\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    beginTime: ").append(toIndentedString(beginTime)).append("\n");
    sb.append("    lastTime: ").append(toIndentedString(lastTime)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    processing: ").append(toIndentedString(processing)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

