/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime.
 */
@ApiModel(description = "The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:24:47.231Z[Etc/UTC]")
public class V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities {
  public static final String SERIALIZED_NAME_ADD = "add";
  @SerializedName(SERIALIZED_NAME_ADD)
  private List<String> add = null;

  public static final String SERIALIZED_NAME_DROP = "drop";
  @SerializedName(SERIALIZED_NAME_DROP)
  private List<String> drop = null;


  public V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities add(List<String> add) {
    
    this.add = add;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities addAddItem(String addItem) {
    if (this.add == null) {
      this.add = new ArrayList<>();
    }
    this.add.add(addItem);
    return this;
  }

   /**
   * Added capabilities
   * @return add
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Added capabilities")

  public List<String> getAdd() {
    return add;
  }


  public void setAdd(List<String> add) {
    this.add = add;
  }


  public V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities drop(List<String> drop) {
    
    this.drop = drop;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities addDropItem(String dropItem) {
    if (this.drop == null) {
      this.drop = new ArrayList<>();
    }
    this.drop.add(dropItem);
    return this;
  }

   /**
   * Removed capabilities
   * @return drop
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Removed capabilities")

  public List<String> getDrop() {
    return drop;
  }


  public void setDrop(List<String> drop) {
    this.drop = drop;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities v1alpha1PodDecorationSpecTemplateSecurityContextCapabilities = (V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities) o;
    return Objects.equals(this.add, v1alpha1PodDecorationSpecTemplateSecurityContextCapabilities.add) &&
        Objects.equals(this.drop, v1alpha1PodDecorationSpecTemplateSecurityContextCapabilities.drop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, drop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodDecorationSpecTemplateSecurityContextCapabilities {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    drop: ").append(toIndentedString(drop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

