/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateEnv;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplateVolumeMounts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1PodDecorationSpecTemplatePrimaryContainers
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:24:47.231Z[Etc/UTC]")
public class V1alpha1PodDecorationSpecTemplatePrimaryContainers {
  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  private List<V1alpha1PodDecorationSpecTemplateEnv> env = null;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TARGET_POLICY = "targetPolicy";
  @SerializedName(SERIALIZED_NAME_TARGET_POLICY)
  private String targetPolicy;

  public static final String SERIALIZED_NAME_VOLUME_MOUNTS = "volumeMounts";
  @SerializedName(SERIALIZED_NAME_VOLUME_MOUNTS)
  private List<V1alpha1PodDecorationSpecTemplateVolumeMounts> volumeMounts = null;


  public V1alpha1PodDecorationSpecTemplatePrimaryContainers env(List<V1alpha1PodDecorationSpecTemplateEnv> env) {
    
    this.env = env;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplatePrimaryContainers addEnvItem(V1alpha1PodDecorationSpecTemplateEnv envItem) {
    if (this.env == null) {
      this.env = new ArrayList<>();
    }
    this.env.add(envItem);
    return this;
  }

   /**
   * AppEnvs is the env variables that will be injected into application container.
   * @return env
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "AppEnvs is the env variables that will be injected into application container.")

  public List<V1alpha1PodDecorationSpecTemplateEnv> getEnv() {
    return env;
  }


  public void setEnv(List<V1alpha1PodDecorationSpecTemplateEnv> env) {
    this.env = env;
  }


  public V1alpha1PodDecorationSpecTemplatePrimaryContainers image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * Image indicates a new image to override the one in application container.
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Image indicates a new image to override the one in application container.")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  public V1alpha1PodDecorationSpecTemplatePrimaryContainers name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name indicates target container name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name indicates target container name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1PodDecorationSpecTemplatePrimaryContainers targetPolicy(String targetPolicy) {
    
    this.targetPolicy = targetPolicy;
    return this;
  }

   /**
   * TargetPolicy indicates which app container these configuration should inject into. Default is LastAppContainerTargetSelectPolicy
   * @return targetPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TargetPolicy indicates which app container these configuration should inject into. Default is LastAppContainerTargetSelectPolicy")

  public String getTargetPolicy() {
    return targetPolicy;
  }


  public void setTargetPolicy(String targetPolicy) {
    this.targetPolicy = targetPolicy;
  }


  public V1alpha1PodDecorationSpecTemplatePrimaryContainers volumeMounts(List<V1alpha1PodDecorationSpecTemplateVolumeMounts> volumeMounts) {
    
    this.volumeMounts = volumeMounts;
    return this;
  }

  public V1alpha1PodDecorationSpecTemplatePrimaryContainers addVolumeMountsItem(V1alpha1PodDecorationSpecTemplateVolumeMounts volumeMountsItem) {
    if (this.volumeMounts == null) {
      this.volumeMounts = new ArrayList<>();
    }
    this.volumeMounts.add(volumeMountsItem);
    return this;
  }

   /**
   * VolumeMounts indicates the volume mount list which is injected into app container volume mount list.
   * @return volumeMounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VolumeMounts indicates the volume mount list which is injected into app container volume mount list.")

  public List<V1alpha1PodDecorationSpecTemplateVolumeMounts> getVolumeMounts() {
    return volumeMounts;
  }


  public void setVolumeMounts(List<V1alpha1PodDecorationSpecTemplateVolumeMounts> volumeMounts) {
    this.volumeMounts = volumeMounts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodDecorationSpecTemplatePrimaryContainers v1alpha1PodDecorationSpecTemplatePrimaryContainers = (V1alpha1PodDecorationSpecTemplatePrimaryContainers) o;
    return Objects.equals(this.env, v1alpha1PodDecorationSpecTemplatePrimaryContainers.env) &&
        Objects.equals(this.image, v1alpha1PodDecorationSpecTemplatePrimaryContainers.image) &&
        Objects.equals(this.name, v1alpha1PodDecorationSpecTemplatePrimaryContainers.name) &&
        Objects.equals(this.targetPolicy, v1alpha1PodDecorationSpecTemplatePrimaryContainers.targetPolicy) &&
        Objects.equals(this.volumeMounts, v1alpha1PodDecorationSpecTemplatePrimaryContainers.volumeMounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(env, image, name, targetPolicy, volumeMounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodDecorationSpecTemplatePrimaryContainers {\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    targetPolicy: ").append(toIndentedString(targetPolicy)).append("\n");
    sb.append("    volumeMounts: ").append(toIndentedString(volumeMounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

