/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodTransitionRuleStatusDetails;
import io.kusionstack.models.V1alpha1PodTransitionRuleStatusRuleStates;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * PodTransitionRuleStatus defines the observed state of PodTransitionRule
 */
@ApiModel(description = "PodTransitionRuleStatus defines the observed state of PodTransitionRule")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:52:16.042Z[Etc/UTC]")
public class V1alpha1PodTransitionRuleStatus {
  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private List<V1alpha1PodTransitionRuleStatusDetails> details = null;

  public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
  @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
  private Long observedGeneration;

  public static final String SERIALIZED_NAME_RULE_STATES = "ruleStates";
  @SerializedName(SERIALIZED_NAME_RULE_STATES)
  private List<V1alpha1PodTransitionRuleStatusRuleStates> ruleStates = null;

  public static final String SERIALIZED_NAME_TARGETS = "targets";
  @SerializedName(SERIALIZED_NAME_TARGETS)
  private List<String> targets = null;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "updateTime";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  private OffsetDateTime updateTime;


  public V1alpha1PodTransitionRuleStatus details(List<V1alpha1PodTransitionRuleStatusDetails> details) {
    
    this.details = details;
    return this;
  }

  public V1alpha1PodTransitionRuleStatus addDetailsItem(V1alpha1PodTransitionRuleStatusDetails detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Details contains all pods podtransitionrule details
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details contains all pods podtransitionrule details")

  public List<V1alpha1PodTransitionRuleStatusDetails> getDetails() {
    return details;
  }


  public void setDetails(List<V1alpha1PodTransitionRuleStatusDetails> details) {
    this.details = details;
  }


  public V1alpha1PodTransitionRuleStatus observedGeneration(Long observedGeneration) {
    
    this.observedGeneration = observedGeneration;
    return this;
  }

   /**
   * ObservedGeneration is the most recent generation observed for PodTransitionRule
   * @return observedGeneration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ObservedGeneration is the most recent generation observed for PodTransitionRule")

  public Long getObservedGeneration() {
    return observedGeneration;
  }


  public void setObservedGeneration(Long observedGeneration) {
    this.observedGeneration = observedGeneration;
  }


  public V1alpha1PodTransitionRuleStatus ruleStates(List<V1alpha1PodTransitionRuleStatusRuleStates> ruleStates) {
    
    this.ruleStates = ruleStates;
    return this;
  }

  public V1alpha1PodTransitionRuleStatus addRuleStatesItem(V1alpha1PodTransitionRuleStatusRuleStates ruleStatesItem) {
    if (this.ruleStates == null) {
      this.ruleStates = new ArrayList<>();
    }
    this.ruleStates.add(ruleStatesItem);
    return this;
  }

   /**
   * RuleStates contains the RuleState resource info in webhook processing progress.
   * @return ruleStates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RuleStates contains the RuleState resource info in webhook processing progress.")

  public List<V1alpha1PodTransitionRuleStatusRuleStates> getRuleStates() {
    return ruleStates;
  }


  public void setRuleStates(List<V1alpha1PodTransitionRuleStatusRuleStates> ruleStates) {
    this.ruleStates = ruleStates;
  }


  public V1alpha1PodTransitionRuleStatus targets(List<String> targets) {
    
    this.targets = targets;
    return this;
  }

  public V1alpha1PodTransitionRuleStatus addTargetsItem(String targetsItem) {
    if (this.targets == null) {
      this.targets = new ArrayList<>();
    }
    this.targets.add(targetsItem);
    return this;
  }

   /**
   * Targets contains the target resource names this PodTransitionRule is able to select.
   * @return targets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Targets contains the target resource names this PodTransitionRule is able to select.")

  public List<String> getTargets() {
    return targets;
  }


  public void setTargets(List<String> targets) {
    this.targets = targets;
  }


  public V1alpha1PodTransitionRuleStatus updateTime(OffsetDateTime updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }


  public void setUpdateTime(OffsetDateTime updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodTransitionRuleStatus v1alpha1PodTransitionRuleStatus = (V1alpha1PodTransitionRuleStatus) o;
    return Objects.equals(this.details, v1alpha1PodTransitionRuleStatus.details) &&
        Objects.equals(this.observedGeneration, v1alpha1PodTransitionRuleStatus.observedGeneration) &&
        Objects.equals(this.ruleStates, v1alpha1PodTransitionRuleStatus.ruleStates) &&
        Objects.equals(this.targets, v1alpha1PodTransitionRuleStatus.targets) &&
        Objects.equals(this.updateTime, v1alpha1PodTransitionRuleStatus.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, observedGeneration, ruleStates, targets, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodTransitionRuleStatus {\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
    sb.append("    ruleStates: ").append(toIndentedString(ruleStates)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

