/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodDecorationSpecSelector;
import io.kusionstack.models.V1alpha1PodDecorationSpecTemplate;
import io.kusionstack.models.V1alpha1PodDecorationSpecUpdateStrategy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PodDecorationSpec defines the desired state of PodDecoration
 */
@ApiModel(description = "PodDecorationSpec defines the desired state of PodDecoration")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:24:47.231Z[Etc/UTC]")
public class V1alpha1PodDecorationSpec {
  public static final String SERIALIZED_NAME_DISABLE_POD_DETAIL = "disablePodDetail";
  @SerializedName(SERIALIZED_NAME_DISABLE_POD_DETAIL)
  private Boolean disablePodDetail;

  public static final String SERIALIZED_NAME_HISTORY_LIMIT = "historyLimit";
  @SerializedName(SERIALIZED_NAME_HISTORY_LIMIT)
  private Integer historyLimit;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private V1alpha1PodDecorationSpecSelector selector;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private V1alpha1PodDecorationSpecTemplate template;

  public static final String SERIALIZED_NAME_UPDATE_STRATEGY = "updateStrategy";
  @SerializedName(SERIALIZED_NAME_UPDATE_STRATEGY)
  private V1alpha1PodDecorationSpecUpdateStrategy updateStrategy;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  private Integer weight;


  public V1alpha1PodDecorationSpec disablePodDetail(Boolean disablePodDetail) {
    
    this.disablePodDetail = disablePodDetail;
    return this;
  }

   /**
   * DisablePodDetail used to disable show status pod details
   * @return disablePodDetail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DisablePodDetail used to disable show status pod details")

  public Boolean getDisablePodDetail() {
    return disablePodDetail;
  }


  public void setDisablePodDetail(Boolean disablePodDetail) {
    this.disablePodDetail = disablePodDetail;
  }


  public V1alpha1PodDecorationSpec historyLimit(Integer historyLimit) {
    
    this.historyLimit = historyLimit;
    return this;
  }

   /**
   * Indicate the number of histories to be conserved If unspecified, defaults to 20
   * @return historyLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicate the number of histories to be conserved If unspecified, defaults to 20")

  public Integer getHistoryLimit() {
    return historyLimit;
  }


  public void setHistoryLimit(Integer historyLimit) {
    this.historyLimit = historyLimit;
  }


  public V1alpha1PodDecorationSpec selector(V1alpha1PodDecorationSpecSelector selector) {
    
    this.selector = selector;
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodDecorationSpecSelector getSelector() {
    return selector;
  }


  public void setSelector(V1alpha1PodDecorationSpecSelector selector) {
    this.selector = selector;
  }


  public V1alpha1PodDecorationSpec template(V1alpha1PodDecorationSpecTemplate template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodDecorationSpecTemplate getTemplate() {
    return template;
  }


  public void setTemplate(V1alpha1PodDecorationSpecTemplate template) {
    this.template = template;
  }


  public V1alpha1PodDecorationSpec updateStrategy(V1alpha1PodDecorationSpecUpdateStrategy updateStrategy) {
    
    this.updateStrategy = updateStrategy;
    return this;
  }

   /**
   * Get updateStrategy
   * @return updateStrategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodDecorationSpecUpdateStrategy getUpdateStrategy() {
    return updateStrategy;
  }


  public void setUpdateStrategy(V1alpha1PodDecorationSpecUpdateStrategy updateStrategy) {
    this.updateStrategy = updateStrategy;
  }


  public V1alpha1PodDecorationSpec weight(Integer weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * Weight indicates the priority to apply for a group of PodDecorations with same group value. The greater one has higher priority to apply. Default value is 0.
   * @return weight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Weight indicates the priority to apply for a group of PodDecorations with same group value. The greater one has higher priority to apply. Default value is 0.")

  public Integer getWeight() {
    return weight;
  }


  public void setWeight(Integer weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodDecorationSpec v1alpha1PodDecorationSpec = (V1alpha1PodDecorationSpec) o;
    return Objects.equals(this.disablePodDetail, v1alpha1PodDecorationSpec.disablePodDetail) &&
        Objects.equals(this.historyLimit, v1alpha1PodDecorationSpec.historyLimit) &&
        Objects.equals(this.selector, v1alpha1PodDecorationSpec.selector) &&
        Objects.equals(this.template, v1alpha1PodDecorationSpec.template) &&
        Objects.equals(this.updateStrategy, v1alpha1PodDecorationSpec.updateStrategy) &&
        Objects.equals(this.weight, v1alpha1PodDecorationSpec.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disablePodDetail, historyLimit, selector, template, updateStrategy, weight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodDecorationSpec {\n");
    sb.append("    disablePodDetail: ").append(toIndentedString(disablePodDetail)).append("\n");
    sb.append("    historyLimit: ").append(toIndentedString(historyLimit)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    updateStrategy: ").append(toIndentedString(updateStrategy)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

