/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1PodDecorationStatusDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PodDecorationStatus defines the observed state of PodDecoration
 */
@ApiModel(description = "PodDecorationStatus defines the observed state of PodDecoration")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:24:47.231Z[Etc/UTC]")
public class V1alpha1PodDecorationStatus {
  public static final String SERIALIZED_NAME_COLLISION_COUNT = "collisionCount";
  @SerializedName(SERIALIZED_NAME_COLLISION_COUNT)
  private Integer collisionCount;

  public static final String SERIALIZED_NAME_CURRENT_REVISION = "currentRevision";
  @SerializedName(SERIALIZED_NAME_CURRENT_REVISION)
  private String currentRevision;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private List<V1alpha1PodDecorationStatusDetails> details = null;

  public static final String SERIALIZED_NAME_INJECTED_PODS = "injectedPods";
  @SerializedName(SERIALIZED_NAME_INJECTED_PODS)
  private Integer injectedPods;

  public static final String SERIALIZED_NAME_MATCHED_PODS = "matchedPods";
  @SerializedName(SERIALIZED_NAME_MATCHED_PODS)
  private Integer matchedPods;

  public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
  @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
  private Long observedGeneration;

  public static final String SERIALIZED_NAME_UPDATED_AVAILABLE_PODS = "updatedAvailablePods";
  @SerializedName(SERIALIZED_NAME_UPDATED_AVAILABLE_PODS)
  private Integer updatedAvailablePods;

  public static final String SERIALIZED_NAME_UPDATED_PODS = "updatedPods";
  @SerializedName(SERIALIZED_NAME_UPDATED_PODS)
  private Integer updatedPods;

  public static final String SERIALIZED_NAME_UPDATED_READY_PODS = "updatedReadyPods";
  @SerializedName(SERIALIZED_NAME_UPDATED_READY_PODS)
  private Integer updatedReadyPods;

  public static final String SERIALIZED_NAME_UPDATED_REVISION = "updatedRevision";
  @SerializedName(SERIALIZED_NAME_UPDATED_REVISION)
  private String updatedRevision;


  public V1alpha1PodDecorationStatus collisionCount(Integer collisionCount) {
    
    this.collisionCount = collisionCount;
    return this;
  }

   /**
   * Count of hash collisions for the PodDecoration. The PodDecoration controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision.
   * @return collisionCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of hash collisions for the PodDecoration. The PodDecoration controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision.")

  public Integer getCollisionCount() {
    return collisionCount;
  }


  public void setCollisionCount(Integer collisionCount) {
    this.collisionCount = collisionCount;
  }


  public V1alpha1PodDecorationStatus currentRevision(String currentRevision) {
    
    this.currentRevision = currentRevision;
    return this;
  }

   /**
   * CurrentRevision, if not empty, indicates the version of the PodDecoration.
   * @return currentRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CurrentRevision, if not empty, indicates the version of the PodDecoration.")

  public String getCurrentRevision() {
    return currentRevision;
  }


  public void setCurrentRevision(String currentRevision) {
    this.currentRevision = currentRevision;
  }


  public V1alpha1PodDecorationStatus details(List<V1alpha1PodDecorationStatusDetails> details) {
    
    this.details = details;
    return this;
  }

  public V1alpha1PodDecorationStatus addDetailsItem(V1alpha1PodDecorationStatusDetails detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Details record the update information of CollaSets and Pods
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details record the update information of CollaSets and Pods")

  public List<V1alpha1PodDecorationStatusDetails> getDetails() {
    return details;
  }


  public void setDetails(List<V1alpha1PodDecorationStatusDetails> details) {
    this.details = details;
  }


  public V1alpha1PodDecorationStatus injectedPods(Integer injectedPods) {
    
    this.injectedPods = injectedPods;
    return this;
  }

   /**
   * InjectedPods is the number of injected Pods that are injected with this PodDecoration
   * @return injectedPods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "InjectedPods is the number of injected Pods that are injected with this PodDecoration")

  public Integer getInjectedPods() {
    return injectedPods;
  }


  public void setInjectedPods(Integer injectedPods) {
    this.injectedPods = injectedPods;
  }


  public V1alpha1PodDecorationStatus matchedPods(Integer matchedPods) {
    
    this.matchedPods = matchedPods;
    return this;
  }

   /**
   * MatchedPods is the number of Pods whose labels are matched with this PodDecoration&#39;s selector
   * @return matchedPods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MatchedPods is the number of Pods whose labels are matched with this PodDecoration's selector")

  public Integer getMatchedPods() {
    return matchedPods;
  }


  public void setMatchedPods(Integer matchedPods) {
    this.matchedPods = matchedPods;
  }


  public V1alpha1PodDecorationStatus observedGeneration(Long observedGeneration) {
    
    this.observedGeneration = observedGeneration;
    return this;
  }

   /**
   * ObservedGeneration is the most recent generation observed for this PodDecoration. It corresponds to the PodDecoration&#39;s generation, which is updated on mutation by the API Server.
   * @return observedGeneration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ObservedGeneration is the most recent generation observed for this PodDecoration. It corresponds to the PodDecoration's generation, which is updated on mutation by the API Server.")

  public Long getObservedGeneration() {
    return observedGeneration;
  }


  public void setObservedGeneration(Long observedGeneration) {
    this.observedGeneration = observedGeneration;
  }


  public V1alpha1PodDecorationStatus updatedAvailablePods(Integer updatedAvailablePods) {
    
    this.updatedAvailablePods = updatedAvailablePods;
    return this;
  }

   /**
   * UpdatedAvailablePods indicates the number of available updated revision replicas for this PodDecoration. A pod is updated available means the pod is ready for updated revision and accessible
   * @return updatedAvailablePods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UpdatedAvailablePods indicates the number of available updated revision replicas for this PodDecoration. A pod is updated available means the pod is ready for updated revision and accessible")

  public Integer getUpdatedAvailablePods() {
    return updatedAvailablePods;
  }


  public void setUpdatedAvailablePods(Integer updatedAvailablePods) {
    this.updatedAvailablePods = updatedAvailablePods;
  }


  public V1alpha1PodDecorationStatus updatedPods(Integer updatedPods) {
    
    this.updatedPods = updatedPods;
    return this;
  }

   /**
   * UpdatedPods is the number of matched Pods that are injected with the latest PodDecoration&#39;s containers
   * @return updatedPods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UpdatedPods is the number of matched Pods that are injected with the latest PodDecoration's containers")

  public Integer getUpdatedPods() {
    return updatedPods;
  }


  public void setUpdatedPods(Integer updatedPods) {
    this.updatedPods = updatedPods;
  }


  public V1alpha1PodDecorationStatus updatedReadyPods(Integer updatedReadyPods) {
    
    this.updatedReadyPods = updatedReadyPods;
    return this;
  }

   /**
   * UpdatedReadyPods is the number of matched pods that updated and ready
   * @return updatedReadyPods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UpdatedReadyPods is the number of matched pods that updated and ready")

  public Integer getUpdatedReadyPods() {
    return updatedReadyPods;
  }


  public void setUpdatedReadyPods(Integer updatedReadyPods) {
    this.updatedReadyPods = updatedReadyPods;
  }


  public V1alpha1PodDecorationStatus updatedRevision(String updatedRevision) {
    
    this.updatedRevision = updatedRevision;
    return this;
  }

   /**
   * UpdatedRevision, if not empty, indicates the version of the PodDecoration currently updated.
   * @return updatedRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UpdatedRevision, if not empty, indicates the version of the PodDecoration currently updated.")

  public String getUpdatedRevision() {
    return updatedRevision;
  }


  public void setUpdatedRevision(String updatedRevision) {
    this.updatedRevision = updatedRevision;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PodDecorationStatus v1alpha1PodDecorationStatus = (V1alpha1PodDecorationStatus) o;
    return Objects.equals(this.collisionCount, v1alpha1PodDecorationStatus.collisionCount) &&
        Objects.equals(this.currentRevision, v1alpha1PodDecorationStatus.currentRevision) &&
        Objects.equals(this.details, v1alpha1PodDecorationStatus.details) &&
        Objects.equals(this.injectedPods, v1alpha1PodDecorationStatus.injectedPods) &&
        Objects.equals(this.matchedPods, v1alpha1PodDecorationStatus.matchedPods) &&
        Objects.equals(this.observedGeneration, v1alpha1PodDecorationStatus.observedGeneration) &&
        Objects.equals(this.updatedAvailablePods, v1alpha1PodDecorationStatus.updatedAvailablePods) &&
        Objects.equals(this.updatedPods, v1alpha1PodDecorationStatus.updatedPods) &&
        Objects.equals(this.updatedReadyPods, v1alpha1PodDecorationStatus.updatedReadyPods) &&
        Objects.equals(this.updatedRevision, v1alpha1PodDecorationStatus.updatedRevision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collisionCount, currentRevision, details, injectedPods, matchedPods, observedGeneration, updatedAvailablePods, updatedPods, updatedReadyPods, updatedRevision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PodDecorationStatus {\n");
    sb.append("    collisionCount: ").append(toIndentedString(collisionCount)).append("\n");
    sb.append("    currentRevision: ").append(toIndentedString(currentRevision)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    injectedPods: ").append(toIndentedString(injectedPods)).append("\n");
    sb.append("    matchedPods: ").append(toIndentedString(matchedPods)).append("\n");
    sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
    sb.append("    updatedAvailablePods: ").append(toIndentedString(updatedAvailablePods)).append("\n");
    sb.append("    updatedPods: ").append(toIndentedString(updatedPods)).append("\n");
    sb.append("    updatedReadyPods: ").append(toIndentedString(updatedReadyPods)).append("\n");
    sb.append("    updatedRevision: ").append(toIndentedString(updatedRevision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

