/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kusionstack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kusionstack.models.V1alpha1CollaSetStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CollaSetStatus defines the observed state of CollaSet
 */
@ApiModel(description = "CollaSetStatus defines the observed state of CollaSet")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-22T06:19:56.968Z[Etc/UTC]")
public class V1alpha1CollaSetStatus {
  public static final String SERIALIZED_NAME_AVAILABLE_REPLICAS = "availableReplicas";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_REPLICAS)
  private Integer availableReplicas;

  public static final String SERIALIZED_NAME_COLLISION_COUNT = "collisionCount";
  @SerializedName(SERIALIZED_NAME_COLLISION_COUNT)
  private Integer collisionCount;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha1CollaSetStatusConditions> conditions = null;

  public static final String SERIALIZED_NAME_CURRENT_REVISION = "currentRevision";
  @SerializedName(SERIALIZED_NAME_CURRENT_REVISION)
  private String currentRevision;

  public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
  @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
  private Long observedGeneration;

  public static final String SERIALIZED_NAME_OPERATING_REPLICAS = "operatingReplicas";
  @SerializedName(SERIALIZED_NAME_OPERATING_REPLICAS)
  private Integer operatingReplicas;

  public static final String SERIALIZED_NAME_READY_REPLICAS = "readyReplicas";
  @SerializedName(SERIALIZED_NAME_READY_REPLICAS)
  private Integer readyReplicas;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_SCHEDULED_REPLICAS = "scheduledReplicas";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_REPLICAS)
  private Integer scheduledReplicas;

  public static final String SERIALIZED_NAME_UPDATED_AVAILABLE_REPLICAS = "updatedAvailableReplicas";
  @SerializedName(SERIALIZED_NAME_UPDATED_AVAILABLE_REPLICAS)
  private Integer updatedAvailableReplicas;

  public static final String SERIALIZED_NAME_UPDATED_READY_REPLICAS = "updatedReadyReplicas";
  @SerializedName(SERIALIZED_NAME_UPDATED_READY_REPLICAS)
  private Integer updatedReadyReplicas;

  public static final String SERIALIZED_NAME_UPDATED_REPLICAS = "updatedReplicas";
  @SerializedName(SERIALIZED_NAME_UPDATED_REPLICAS)
  private Integer updatedReplicas;

  public static final String SERIALIZED_NAME_UPDATED_REVISION = "updatedRevision";
  @SerializedName(SERIALIZED_NAME_UPDATED_REVISION)
  private String updatedRevision;


  public V1alpha1CollaSetStatus availableReplicas(Integer availableReplicas) {
    
    this.availableReplicas = availableReplicas;
    return this;
  }

   /**
   * The number of available replicas (ready for at least minReadySeconds) for this replica set.
   * @return availableReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of available replicas (ready for at least minReadySeconds) for this replica set.")

  public Integer getAvailableReplicas() {
    return availableReplicas;
  }


  public void setAvailableReplicas(Integer availableReplicas) {
    this.availableReplicas = availableReplicas;
  }


  public V1alpha1CollaSetStatus collisionCount(Integer collisionCount) {
    
    this.collisionCount = collisionCount;
    return this;
  }

   /**
   * Count of hash collisions for the CollaSet. The CollaSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision.
   * @return collisionCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of hash collisions for the CollaSet. The CollaSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision.")

  public Integer getCollisionCount() {
    return collisionCount;
  }


  public void setCollisionCount(Integer collisionCount) {
    this.collisionCount = collisionCount;
  }


  public V1alpha1CollaSetStatus conditions(List<V1alpha1CollaSetStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha1CollaSetStatus addConditionsItem(V1alpha1CollaSetStatusConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Represents the latest available observations of a CollaSet&#39;s current state.
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Represents the latest available observations of a CollaSet's current state.")

  public List<V1alpha1CollaSetStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha1CollaSetStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1alpha1CollaSetStatus currentRevision(String currentRevision) {
    
    this.currentRevision = currentRevision;
    return this;
  }

   /**
   * CurrentRevision, if not empty, indicates the version of the CollaSet.
   * @return currentRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CurrentRevision, if not empty, indicates the version of the CollaSet.")

  public String getCurrentRevision() {
    return currentRevision;
  }


  public void setCurrentRevision(String currentRevision) {
    this.currentRevision = currentRevision;
  }


  public V1alpha1CollaSetStatus observedGeneration(Long observedGeneration) {
    
    this.observedGeneration = observedGeneration;
    return this;
  }

   /**
   * ObservedGeneration is the most recent generation observed for this CollaSet. It corresponds to the CollaSet&#39;s generation, which is updated on mutation by the API Server.
   * @return observedGeneration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ObservedGeneration is the most recent generation observed for this CollaSet. It corresponds to the CollaSet's generation, which is updated on mutation by the API Server.")

  public Long getObservedGeneration() {
    return observedGeneration;
  }


  public void setObservedGeneration(Long observedGeneration) {
    this.observedGeneration = observedGeneration;
  }


  public V1alpha1CollaSetStatus operatingReplicas(Integer operatingReplicas) {
    
    this.operatingReplicas = operatingReplicas;
    return this;
  }

   /**
   * OperatingReplicas indicates the number of pods during pod ops lifecycle and not finish update-phase.
   * @return operatingReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "OperatingReplicas indicates the number of pods during pod ops lifecycle and not finish update-phase.")

  public Integer getOperatingReplicas() {
    return operatingReplicas;
  }


  public void setOperatingReplicas(Integer operatingReplicas) {
    this.operatingReplicas = operatingReplicas;
  }


  public V1alpha1CollaSetStatus readyReplicas(Integer readyReplicas) {
    
    this.readyReplicas = readyReplicas;
    return this;
  }

   /**
   * ReadyReplicas indicates the number of the pod with ready condition
   * @return readyReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ReadyReplicas indicates the number of the pod with ready condition")

  public Integer getReadyReplicas() {
    return readyReplicas;
  }


  public void setReadyReplicas(Integer readyReplicas) {
    this.readyReplicas = readyReplicas;
  }


  public V1alpha1CollaSetStatus replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Replicas is the most recently observed number of replicas.
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Replicas is the most recently observed number of replicas.")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1alpha1CollaSetStatus scheduledReplicas(Integer scheduledReplicas) {
    
    this.scheduledReplicas = scheduledReplicas;
    return this;
  }

   /**
   * the number of scheduled replicas for the CollaSet.
   * @return scheduledReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the number of scheduled replicas for the CollaSet.")

  public Integer getScheduledReplicas() {
    return scheduledReplicas;
  }


  public void setScheduledReplicas(Integer scheduledReplicas) {
    this.scheduledReplicas = scheduledReplicas;
  }


  public V1alpha1CollaSetStatus updatedAvailableReplicas(Integer updatedAvailableReplicas) {
    
    this.updatedAvailableReplicas = updatedAvailableReplicas;
    return this;
  }

   /**
   * UpdatedAvailableReplicas indicates the number of available updated revision replicas for this CollaSet. A pod is updated available means the pod is ready for updated revision and accessible
   * @return updatedAvailableReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UpdatedAvailableReplicas indicates the number of available updated revision replicas for this CollaSet. A pod is updated available means the pod is ready for updated revision and accessible")

  public Integer getUpdatedAvailableReplicas() {
    return updatedAvailableReplicas;
  }


  public void setUpdatedAvailableReplicas(Integer updatedAvailableReplicas) {
    this.updatedAvailableReplicas = updatedAvailableReplicas;
  }


  public V1alpha1CollaSetStatus updatedReadyReplicas(Integer updatedReadyReplicas) {
    
    this.updatedReadyReplicas = updatedReadyReplicas;
    return this;
  }

   /**
   * UpdatedReadyReplicas indicates the number of the pod with updated revision and ready condition
   * @return updatedReadyReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UpdatedReadyReplicas indicates the number of the pod with updated revision and ready condition")

  public Integer getUpdatedReadyReplicas() {
    return updatedReadyReplicas;
  }


  public void setUpdatedReadyReplicas(Integer updatedReadyReplicas) {
    this.updatedReadyReplicas = updatedReadyReplicas;
  }


  public V1alpha1CollaSetStatus updatedReplicas(Integer updatedReplicas) {
    
    this.updatedReplicas = updatedReplicas;
    return this;
  }

   /**
   * The number of pods in updated version.
   * @return updatedReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of pods in updated version.")

  public Integer getUpdatedReplicas() {
    return updatedReplicas;
  }


  public void setUpdatedReplicas(Integer updatedReplicas) {
    this.updatedReplicas = updatedReplicas;
  }


  public V1alpha1CollaSetStatus updatedRevision(String updatedRevision) {
    
    this.updatedRevision = updatedRevision;
    return this;
  }

   /**
   * UpdatedRevision, if not empty, indicates the version of the CollaSet currently updated.
   * @return updatedRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UpdatedRevision, if not empty, indicates the version of the CollaSet currently updated.")

  public String getUpdatedRevision() {
    return updatedRevision;
  }


  public void setUpdatedRevision(String updatedRevision) {
    this.updatedRevision = updatedRevision;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CollaSetStatus v1alpha1CollaSetStatus = (V1alpha1CollaSetStatus) o;
    return Objects.equals(this.availableReplicas, v1alpha1CollaSetStatus.availableReplicas) &&
        Objects.equals(this.collisionCount, v1alpha1CollaSetStatus.collisionCount) &&
        Objects.equals(this.conditions, v1alpha1CollaSetStatus.conditions) &&
        Objects.equals(this.currentRevision, v1alpha1CollaSetStatus.currentRevision) &&
        Objects.equals(this.observedGeneration, v1alpha1CollaSetStatus.observedGeneration) &&
        Objects.equals(this.operatingReplicas, v1alpha1CollaSetStatus.operatingReplicas) &&
        Objects.equals(this.readyReplicas, v1alpha1CollaSetStatus.readyReplicas) &&
        Objects.equals(this.replicas, v1alpha1CollaSetStatus.replicas) &&
        Objects.equals(this.scheduledReplicas, v1alpha1CollaSetStatus.scheduledReplicas) &&
        Objects.equals(this.updatedAvailableReplicas, v1alpha1CollaSetStatus.updatedAvailableReplicas) &&
        Objects.equals(this.updatedReadyReplicas, v1alpha1CollaSetStatus.updatedReadyReplicas) &&
        Objects.equals(this.updatedReplicas, v1alpha1CollaSetStatus.updatedReplicas) &&
        Objects.equals(this.updatedRevision, v1alpha1CollaSetStatus.updatedRevision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableReplicas, collisionCount, conditions, currentRevision, observedGeneration, operatingReplicas, readyReplicas, replicas, scheduledReplicas, updatedAvailableReplicas, updatedReadyReplicas, updatedReplicas, updatedRevision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CollaSetStatus {\n");
    sb.append("    availableReplicas: ").append(toIndentedString(availableReplicas)).append("\n");
    sb.append("    collisionCount: ").append(toIndentedString(collisionCount)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    currentRevision: ").append(toIndentedString(currentRevision)).append("\n");
    sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
    sb.append("    operatingReplicas: ").append(toIndentedString(operatingReplicas)).append("\n");
    sb.append("    readyReplicas: ").append(toIndentedString(readyReplicas)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    scheduledReplicas: ").append(toIndentedString(scheduledReplicas)).append("\n");
    sb.append("    updatedAvailableReplicas: ").append(toIndentedString(updatedAvailableReplicas)).append("\n");
    sb.append("    updatedReadyReplicas: ").append(toIndentedString(updatedReadyReplicas)).append("\n");
    sb.append("    updatedReplicas: ").append(toIndentedString(updatedReplicas)).append("\n");
    sb.append("    updatedRevision: ").append(toIndentedString(updatedRevision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

